### ISSUE TITLE
打补丁失败

### ISSUE THREAD

**Issue by alawnchen** [yaoweibin/nginx_tcp_proxy_module#132]
我的nginx版本是1.10.15。我在打补丁的时候看到两条失败提示，导致编译的时候老是出错。不知道是不是不支持nginx1.10.15，我又该怎么处理？有点困扰，烦请帮忙，谢谢！！
![2016-08-13 02 20 30](https://cloud.githubusercontent.com/assets/1811463/17632735/8c9b376a-60fc-11e6-84fa-6c3e8adca484.jpg)

**Comment by medzeus2** [comment]
这2个问题还好拉。
第一个问题在 ngx_log.c文件中 找到 debug_levels 定义 增加 "debug_tcp"，
在ngx_log.h文件中 
#define NGX_LOG_DEBUG_STREAM      0x400
的下面增加
#define NGX_LOG_DEBUG_TCP         0x800

修改
#define NGX_LOG_DEBUG_LAST        NGX_LOG_DEBUG_TCP
就行了。

**Comment by alawnchen** [comment]
@medzeus2 多谢，我试试

**Comment by medzeus2** [comment]
https://raw.githubusercontent.com/medzeus2/nginx_tcp_proxy_module/master/tcp_1_8.patch
1.8 -1.10的patch 最新版本支持 make了。

**Comment by alawnchen** [comment]
@medzeus2 成功了，谢谢！！
