### ISSUE TITLE
nginx-1.10.1编译模块报错 duplicate member ‘check_index’

### ISSUE THREAD

**Issue by sweet66** [yaoweibin/nginx_tcp_proxy_module#144]
已经打上tcp.patch补丁  patch -p1 < ../nginx_tcp_proxy_module/tcp.patch   但还是报错**src/http/ngx_http_upstream_round_robin.h:43: error: duplicate member ‘check_index’
src/http/ngx_http_upstream_round_robin.h:47: error: duplicate member ‘check_index’
src/http/ngx_http_upstream_round_robin.h:51: error: duplicate member ‘check_index’
src/http/ngx_http_upstream_round_robin.h:55: error: duplicate member ‘check_index’
src/http/ngx_http_upstream_round_robin.h:59: error: duplicate member ‘check_index’
make[1]: *** [objs/src/http/ngx_http.o] Error 1
make[1]: Leaving directory `/root/online/nginx/nginx-1.10.1**'

**Comment by wealthjackson1** [comment]
同样的问题编译出现在nginx-1.14.0

**Comment by larryluo64** [comment]
src/http/ngx_http_upstream_round_robin.h:62:37: error: duplicate member ‘check_index’

**Comment by larryluo64** [comment]
我的也出现同样的问题，你的解决了没？

**Comment by sweet66** [comment]
解决了，得把之前编译过的nginx目录删除重新编译

larryluo64 <notifications@github.com> 于2019年4月16日周二 下午4:04写道：
