### ISSUE TITLE
Websocket closing after a minute of being idle

### ISSUE THREAD

**Issue by watterssn** [yaoweibin/nginx_tcp_proxy_module#16]
First off thanks for this module! Been searching everywhere to get websockets to work through a proxy.  I'm having an issue though that I am not seeing in development.  When in production (and behind nginx), the socket is closing after a minute of being idle.  Is this expected behavior?  Do I need to do anything to keep it alive?

Thanks!

**Comment by abhi2687** [comment]
Hi I have tried this solution but getting message "timeout" directive is not allowed here in....can you suggest which is the right place

**Comment by bcicen** [comment]
@abhi2687 proxy_read_timeout should be valid in any server block

**Comment by akmintro** [comment]
@yaoweibin What did you mean and where should 'timeout 86400s' command be added?

**Comment by RayOsLei** [comment]
@yaoweibin  "timeout" directive is not allowed here
