### ISSUE TITLE
"tcp" directive is not allowed here

### ISSUE THREAD

**Issue by tanepiper** [yaoweibin/nginx_tcp_proxy_module#51]
Hi there,

I have a websocket application that runs on a port on the local machine - I've recompiled nginx 1.2.3 with the TCP module, and have created a file for sites-enabled/dashboard.conf.

The file is as follows:

    tcp {
        upstream websockets {
            server 127.0.0.1:35005;
            server 127.0.0.1:35005;

            check interval=3000 rise=2 fall=5 timeout=1000;
        }

        server {
            listen  1270.0.01:80;
            server_name     dashboard.foo.com;
            access_log      /var/log/nginx/foo.dashboard.access.log;

            tcp_nodelay on;
            proxy_pass websockets
        }
    }

However I get an error:

Restarting nginx: nginx: [emerg] "tcp" directive is not allowed here in /etc/nginx/sites-enabled/dashboard.conf:1

This server runs multiple subdomains for this application, with the dashboard subdomain being the only one currently needing websockets.

Any ideas how I can get this working?

**Comment by giasek** [comment]
Can You, please, explain how to use auth_basic, auth_basic_user_file inside tcp block ?
