### ISSUE TITLE
reverse proxy tcp and http on the same port

### ISSUE THREAD

**Issue by beurdouche** [yaoweibin/nginx_tcp_proxy_module#73]
Hello, 
I am having an unfortunate problem but I am not sure if it depends on your module or on nginx...

I want to set nginx to listen to port 443 for both https and websocket streams and reverse proxify them to a webserver and a nodejs so browsers don't trigger the "external content" security alert

Problem is: it seems I can't bind to the same port =s 
Is there something to do ?

Thanks ! B.

<code>
tcp {
    upstream websockets {
        server 127.0.0.1:5050;
        check interval=3000 rise=2 fall=5 timeout=1000;
    }
    server {
      listen 8080;
      proxy_pass websockets;
   }
}

http {
    index index.html index.htm index.php;
    upstream webserver {
        server 127.0.0.1:8080;
    }
    server {
        listen  8080;
        server_name .blabla.com;
        location / {
                proxy_pass      http://webserver;
        }
    }
}
</code>

**Comment by hennihaus** [comment]
Are there any news regarding this issue?

**Comment by yaoweibin** [comment]
No, it should not be used in the same port.
